version: '3.7'
services:
  app:
    build: .
    container_name: "sample_ridgepole_app"
    ports:
      - "3000:3000"
    command: bundle exec rails server
    volumes:
      - .:/sample-ridgepole
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0.13
    container_name: "sample_ridgepole_db"
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/docker:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
